version: '3.9'

services:
  database:
    image: mysql
    platform: linux/x86_64
    container_name: b7teste
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'senhasupersecreta'
      MYSQL_DATABASE: 'b7back'
    ports:
      - '3306:3306'
